# syntax=docker/dockerfile:1

# Toolchain versions follow godotengine/build-containers@bc0a7d9 for Godot 4.5.
ARG FEDORA_VERSION=42
FROM fedora:${FEDORA_VERSION}

ARG SCONS_VERSION=4.9.1
ARG GODOT_LINUX_SDK_VERSION=godot-2023.08.x-4

ENV GODOT_SDK_LINUX_X86_64=/opt/x86_64-godot-linux-gnu_sdk-buildroot

WORKDIR /workspace

RUN dnf -y install --setopt=install_weak_deps=False \
        bash binutils bzip2 curl file findutils gettext git make patch pkgconf-pkg-config \
        python3-pip unzip wayland-devel which xz zip && \
    dnf clean all && \
    python3 -m pip install --no-cache-dir "scons==${SCONS_VERSION}" && \
    curl --fail --location --retry 3 \
        --output /tmp/godot-linux-sdk.tar.bz2 \
        "https://github.com/godotengine/buildroot/releases/download/${GODOT_LINUX_SDK_VERSION}/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2" && \
    tar --extract --bzip2 --file /tmp/godot-linux-sdk.tar.bz2 --directory /opt && \
    rm /tmp/godot-linux-sdk.tar.bz2 && \
    "${GODOT_SDK_LINUX_X86_64}/relocate-sdk.sh"

ENV PATH="${GODOT_SDK_LINUX_X86_64}/bin:${PATH}"

ARG SENTRY_CLI_VERSION=3.8.0

RUN curl --fail --location --retry 3 \
        --output /usr/local/bin/sentry-cli \
        "https://github.com/getsentry/sentry-cli/releases/download/${SENTRY_CLI_VERSION}/sentry-cli-Linux-x86_64" && \
    chmod 0755 /usr/local/bin/sentry-cli && \
    sentry-cli --version

CMD ["/bin/bash"]
